output=$HOME/Documents/reviews-blog/content

echo "Title: $(mpc current --format '%artist% - %album% (%date%)')" > "$output"/"$1"
echo "Date: $(date '+%Y-%m-%d %H:%M')" >> "$output"/"$1"
echo "Category: reviews" >> "$output"/"$1"
echo "Tags:" >> "$output"/"$1"
echo "status: draft" >> "$output"/"$1"
echo "Authors: Rasi" >> "$output"/"$1"
echo "Summary:" >> "$output"/"$1"
echo "sidebarimage: /images/artists/$(mpc current --format '%artist%' | tr " " - | tr '[:upper:]' '[:lower:]').jpg" >> "$output"/"$1"
echo " " >> "$output"/"$1"
echo "<div id=\"covertracks\">" >> "$output"/"$1"
echo "    <div id=\"cover\">" >> "$output"/"$1"
cp "/mnt/wasteland/Audio/Rips/$(dirname "$(mpc current -f '%file%')")/cover.png" "$output"/images/covers/cover-$(mpc current --format '%album%' | tr " " - | tr '[:upper:]' '[:lower:]').jpg
echo "<img src=\"/images/covers/cover-$(mpc current --format '%album%' | tr " " - | tr '[:upper:]' '[:lower:]').jpg\" alt=\"$(mpc current --format '%album%')\">" >> "$output"/"$1"
echo "    </div>" >> "$output"/"$1"
echo "    <div id=\"tracklist\">" >> "$output"/"$1"
echo "$(mpc playlist --format '%track% %title%<br />')" >> "$output"/"$1"
echo "    </div>" >> "$output"/"$1"
echo "</div>" >> "$output"/"$1"
echo " " >> "$output"/"$1"
echo "### Introduction" >> "$output"/"$1"
echo " " >> "$output"/"$1"
echo "### The Sound" >> "$output"/"$1"
echo " " >> "$output"/"$1"
echo "### Preview" >> "$output"/"$1"
echo "<iframe src="https://embed.spotify.com/?uri=SPOTIFY_URI" frameborder="0" allowtransparency="true"></iframe>" >> "$output"/"$1"
echo " " >> "$output"/"$1"
echo "### Weblinks" >> "$output"/"$1"

